a = input('Digite algo: ')
print('Tipo :',type(a))
print('É alfanumérico? ', a.isalnum())
print('É alfabético? ', a.isalpha())
print('É Decimal? ', a.isdecimal())
print('É Digito? ', a.isdigit())
print('É caixa baixa? ', a.islower())
print('É possível imprimir? ', a.isprintable())
print('É caixa alta ? ', a.isupper())